USE HROADS_TARDE;
GO

SELECT * FROM PERSONAGEM

SELECT * FROM CLASSE
SELECT nomeClasse [Nome Classe] FROM CLASSE

SELECT * FROM HABILIDADE
SELECT idHabilidade [ID Habilidade] FROM HABILIDADE

SELECT * FROM TIPO_HABILIDADE

SELECT HABILIDADE.idTipoHabilidade ,nomeHabilidade [Nome Habilidade], tipoHabilidade [Tipo de Habilidade] FROM HABILIDADE
INNER JOIN TIPO_HABILIDADE
ON HABILIDADE.idTipoHabilidade = TIPO_HABILIDADE.idTipoHabilidade;


SELECT PERSONAGEM.idClasse, nomePersonagem [Personagem], nomeClasse [Classe]  FROM PERSONAGEM
INNER JOIN CLASSE
ON CLASSE.idClasse = PERSONAGEM.idClasse;

SELECT PERSONAGEM.idClasse, nomePersonagem [Personagem], nomeClasse [Classe] FROM PERSONAGEM
RIGHT JOIN CLASSE
ON CLASSE.idClasse = PERSONAGEM.idClasse;

SELECT CLASSE.nomeClasse, nomeHabilidade FROM CLASSE
LEFT JOIN CLASSE_HABILIDADE
ON CLASSE_HABILIDADE.idClasse = CLASSE.idClasse
LEFT JOIN HABILIDADE
ON CLASSE_HABILIDADE.idHabilidade = HABILIDADE.idHabilidade;

SELECT HABILIDADE.nomeHabilidade, nomeClasse FROM HABILIDADE
LEFT JOIN CLASSE_HABILIDADE
ON CLASSE_HABILIDADE.idHabilidade = HABILIDADE.idHabilidade
LEFT JOIN CLASSE
ON CLASSE_HABILIDADE.idClasse = CLASSE.idClasse;


SELECT COUNT(idHabilidade) FROM HABILIDADE
Go